### ISSUE TITLE
Update parsing logic to use Babel type guards

### ISSUE THREAD

**Issue by MajorLift** [hb1998/react-component-tree#7]
Hi, it's great to see this project revived. 

I was wondering if the current team might be open to new contributions. 

I briefly worked on updating the sapling parser to use babel type guards instead of tokens for parsing import statements. The code becomes a lot more declarative this way, which should make it easier to maintain and extend features. 

https://github.com/MajorLift/sapling/blob/a52c92be4a2312925deca829753211134546c9bb/sapling/src/SaplingParser.ts#L265-L456

If this doesn't conflict with the general direction the current team is taking, I'd love to take another stab at it. I'm interested in contributing to other areas as well. 

Let me know your thoughts. :)

**Comment by MajorLift** [comment]
Awesome! I'll see if I can make it work with the updates you guys have made, and post a PR when I'm done.

**Comment by hb1998** [comment]
@MajorLift  sounds good
